services:
  app:
    container_name: football_value
    restart: always
    env_file: .env
    build: .
    volumes:
      - app-data:/app/data
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.football.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.football.entrypoints=websecure"
      - "traefik.http.routers.football.tls.certresolver=letsencrypt"
      - "traefik.http.services.football.loadbalancer.server.port=5005"

volumes:
  app-data:

networks:
  traefik-public:
    external: true
